version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    rebase-strategy: "auto"
    labels:
      - "dependencies"
      - "python"
    open-pull-requests-limit: 10
